name: Run Python Script Daily

on:
  schedule:
    - cron: "0 21 * * *"  # Runs daily at 11 PM German time (CET/CEST adjusted)

  workflow_dispatch:  # Allows manual trigger

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Installed Packages
        run: pip list

      - name: Decode Firebase credentials from base64
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS_JSON_B64 }}" | base64 -d > firebase_credentials.json
          CRED_PATH="$(pwd)/firebase_credentials.json"
          printf "FIREBASE_CREDENTIALS_JSON=%s\n" "$CRED_PATH" >> "$GITHUB_ENV"

      - name: Set up environment variables
        run: |
          echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}" >> $GITHUB_ENV
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "TELEGRAM_BOT_CHAT_ID=${{ secrets.TELEGRAM_BOT_CHAT_ID }}" >> $GITHUB_ENV
          echo "HOLDING_STOCKS=${{ secrets.HOLDING_STOCKS }}" >> $GITHUB_ENV
          echo "FIREBASE_CREDENTIALS_JSON=${{ secrets.FIREBASE_CREDENTIALS_JSON }}" >> $GITHUB_ENV
          echo "${{ secrets.FIREBASE_CREDENTIALS_JSON_B64 }}" | base64 -d > firebase_credentials.json
          echo "FIREBASE_CREDENTIALS_JSON=$(pwd)/firebase_credentials.json" >> $GITHUB_ENV

      - name: Run Python Script
        run: python main.py
        env:
          FIREBASE_CREDENTIALS_JSON: ${{ env.FIREBASE_CREDENTIALS_JSON }}
