name: Run Python Script Daily

on:
  schedule:
    - cron: "0 21 * * *"  # Runs daily at 11 PM German time (CET/CEST adjusted)

  workflow_dispatch:  # Allows manual trigger

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Installed Packages
        run: pip list

      - name: Set up Firebase credentials and other environment variables
        run: |
          # Decode Firebase credentials from base64 secret
          echo "${{ secrets.FIREBASE_CREDENTIALS_JSON_B64 }}" | base64 -d > firebase_credentials.json
          
          # Set Firebase credentials path as expected by your code
          echo "FIREBASE_CREDENTIALS=$(pwd)/firebase_credentials.json" >> $GITHUB_ENV
          
          # Set other environment variables
          echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}" >> $GITHUB_ENV
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "TELEGRAM_BOT_CHAT_ID=${{ secrets.TELEGRAM_BOT_CHAT_ID }}" >> $GITHUB_ENV
          echo "HOLDING_STOCKS=${{ secrets.HOLDING_STOCKS }}" >> $GITHUB_ENV

      - name: Verify Firebase credentials
        run: |
          if [ -f "firebase_credentials.json" ]; then
            echo "✅ Firebase credentials file created successfully"
            echo "File size: $(stat -c%s firebase_credentials.json) bytes"
            # Verify it's valid JSON without exposing content
            if python -c "import json; json.load(open('firebase_credentials.json'))"; then
              echo "✅ Firebase credentials JSON is valid"
            else
              echo "❌ Firebase credentials JSON is invalid"
              exit 1
            fi
          else
            echo "❌ Firebase credentials file not found"
            exit 1
          fi
      - name: Run Python Script
        run: python main.py
